### ISSUE TITLE
InvalidParameterValueException: Invalid dead letter ARN: ARNs must start with 'arn:'

### ISSUE THREAD

**Issue by seoker** [motdotla/node-lambda#208]
As I know, the latest release supports the config of Dead Letter Queue, but it seems not compatible with previous settings.
If don't specify the dead letter config explicitly, the config will be `DeadLetterConfig: { TargetArn: '' }` by default, and then it turns into the following error:

```
InvalidParameterValueException: Invalid dead letter ARN: ARNs must start with 'arn:':
    at Object.extractError (/Users/somewhere/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/Users/somewhere/node_modules/aws-sdk/lib/protocol/rest_json.js:37:8)
    at Request.callListeners (/Users/somewhere/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/somewhere/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/somewhere/node_modules/aws-sdk/lib/request.js:673:14)
    at Request.transition (/Users/somewhere/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/somewhere/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/somewhere/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/somewhere/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/somewhere/node_modules/aws-sdk/lib/request.js:675:12)
```

**Comment by seoker** [comment]
Also, I don't know what event source mapping files are and don't want to use it, is there any way to bypass the file exist checking or not setting event_sources.json by default?

**Comment by abetomo** [comment]
@seoker I'm sorry. `InvalidParameterValueException` has been reproduced. to correct.

**Comment by abetomo** [comment]
@seoker seoker I'm sorry. I opened the PR #209 of bugfix.

**Comment by seoker** [comment]
@abetomo Thanks, what a quick resolve! Any thoughts related to `event_sources.json` which I comment in https://github.com/motdotla/node-lambda/issues/208#issuecomment-289970200?

**Comment by abetomo** [comment]
@seoker

`event_sources.json` is created in `node-lambda setup`, but if you are using `0.8.15`, it will not load that file by default.
It must be explicitly specified with `EVENT_SOURCE_FILE` of `.env`  or `-S` option and it will not be loaded.

Is it likely to solve with the above contents?

**Comment by seoker** [comment]
@abetomo 
Thanks, I think I was encountering this issue by `0.8.14` when I was falling back version to test the dead letter config issue. Anyways, waiting for the new version to be released, thanks a lot!

**Comment by abetomo** [comment]
@seoker I think that the modified version has been released, but how about after that?

**Comment by seoker** [comment]
Oh sorry, it's solved by f3ff683b03725a8b3fb91b4751cbed37fae319d9.

**Comment by abetomo** [comment]
Thank you for confirmation!

**Comment by turjachaudhuri** [comment]
I am still getting this issue as of 13.03.2018 . Any ideas on what to do?

**Comment by abetomo** [comment]
@turjachaudhuri What kind of error message is displayed?

**Comment by eberkund** [comment]
I am getting the following with v0.12

```
ValidationException: 1 validation error detected: Value 'arn:aws:iam::aws:policy/AWSLambdaFullAccess' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+
    at Object.extractError (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/protocol/rest_json.js:52:8)
    at Request.callListeners (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/node-lambda/node_modules/aws-sdk/lib/request.js:685:12)
```

**Comment by abetomo** [comment]
@eberkund If I did not specify anything, I did not get an error, but did you specify something?

If nothing is specified, it is set as follows.
```
DeadLetterConfig: { TargetArn: null },
```

**Comment by eberkund** [comment]
For me if nothing is specified it does

```
DeadLetterConfig: { TargetArn: '' }
```

**Comment by abetomo** [comment]
If you do not need the settings, can you delete each line?

https://github.com/motdotla/node-lambda/pull/209#discussion_r108620102

**Comment by eberkund** [comment]
Okay I removed unused entries from my `.env` but I get the same error.

**Comment by abetomo** [comment]
Is it possible to show the command being executed and `.env`.

**Comment by eberkund** [comment]
Ahhh. I found the issue.

I had an old version of `node-lambda` installed globally. I ran the latest version from my node_modules folder and now it works.

Thanks for the help.
